### ISSUE TITLE
User should add content-type as application/json in V2 model for conditions to work.

### ISSUE THREAD

**Issue by ykalidin** [TIBCOSoftware/mashling#151]
While hitting the trigger the content-type needs to be set to application/json for the recipes to work with V2

**Comment by jeffreybozek** [comment]
@ykalidin Can you provide some more details please? Specifically which trigger, which recipes, and what portions of the recipes are not behaving as one would expect?

**Comment by jeffreybozek** [comment]
@jpark800 @rameshpolishetti @ykalidin This is trigger specific. In the case of the Mux trigger the content only gets parsed as JSON if the Content-Type header indicates it should be. You can see here: https://github.com/TIBCOSoftware/mashling/blob/master/ext/flogo/trigger/gorillamuxtrigger/trigger.go#L409

I think this behavior makes sense though, right?

The old conditional evaluation rules still work in that case because it attempts to massage all content to JSON before evaluation.

**Comment by ykalidin** [comment]
Working fine.
Content is parsing as json even if the type is missing or set to text/plain.
