### ISSUE TITLE
Custom gateway binary shows incorrect version

### ISSUE THREAD

**Issue by LakshmiMekala** [TIBCOSoftware/mashling#232]
Get the latest mashilng code and check mashling-cli version.
mashling-cli version : 
Version:  v0.4.1-alpha.1
Build Date:  2018-08-23T13:31:24+0530

Create a custom gateway mashling-cli create -c <mashling.json>
Verify the version of generated mashling gateway binary. 
./mashling-custom/mashling-gateway-linux-amd64 version
Version:  v0.4.0
Build Date:  2018-08-24T07:30:07+0000

Observed mismatch in mashilng version

**Comment by jpark800** [comment]
@jeffreybozek The custom build step in the docker container for the compilation is missing a proper setup of the version before the build. Thus, it picks up the default version (v0.4.0).

**Comment by rameshpolishetti** [comment]
@jeffreybozek PR #238 fixes the issue partially i.e. if the user builds custom gateway using docker option then it works as expected.

There is another scenario to consider i.e. user builds using -N (native option) in a git repository folder (most likely user checks out mashling-recipes git repository and navigate to intended recipe folder). In this case, custom gateway version would be incorrect (mashling-recipes latest tag version would be shown instead of mashling-cli version).

You may consider checking .version file in build.go -> init() first [covers custom gateway case], if not available then get the version from git [covers existing cases]

PS: Adding this redundant comment here as the PR #238 is closed already.

**Comment by LakshmiMekala** [comment]
Verified the issue and observed that it is working fine. 
Hence closing the issue.
